version: '3.8'

services:
  app:
    container_name: graphql-api
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/graphql_server
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    networks:
      - node-network

  mongodb:
    image: mongo:jammy
    ports:
      - '27017:27017'
    volumes:
      - graphql_mongo:/data/db
    networks:
      - node-network

volumes:
  graphql_mongo:

networks:
  node-network:
    driver: bridge
